# Generated by Django 3.0.8 on 2021-03-24 08:26

import apps.common.fileUpload.userPath
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('text', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Etiketler')),
                ('summary', models.CharField(blank=True, max_length=200, verbose_name='Özet')),
                ('content', models.TextField(blank=True, verbose_name='İçerik')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to=apps.common.fileUpload.userPath.userDirectoryPath, verbose_name='Arkaplan Görsel')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=apps.common.fileUpload.userPath.userDirectoryPath, verbose_name='İcon Görsel')),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyuru',
                'ordering': ('date',),
                'permissions': (('liste', 'Listeleme Yetkisi'), ('sil', 'Silme Yetkisi'), ('ekle', 'Ekleme Yetkisi'), ('guncelle', 'Güncelleme Yetkisi')),
                'default_permissions': (),
            },
        ),
    ]
